version: '3'
services:
    notes-app_api-gateway:
        build: 
            context: ./api-gateway
            dockerfile: Dockerfile
        container_name: "notes-app_api-gateway"
        env_file: ./api-gateway/.env
        environment:
            - DOCKER_BUILD=true
        ports:
            - "80:80"
        networks:
            - notes-app_api-service-net
            - notes-app_ui-service-net

    notes-app_api-service:
        build: 
            context: ./api-service
            dockerfile: Dockerfile
        container_name: "notes-app_api-service"
        env_file: ./api-service/.env
        environment:
            - DOCKER_BUILD=true
        ports:
            - "3001:3001"
        hostname: api-service
        networks:
            - redis-net
            - notes-app_api-service-net
        depends_on:
            - redis

    notes-app_ui-service:
        build: 
            context: ./ui-service
            dockerfile: Dockerfile
        container_name: "notes-app_ui-service"
        env_file: ./ui-service/.env
        environment:
            - DOCKER_BUILD=true
        ports:
            - "3000:3000"
        hostname: ui-service

    redis:
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
            - redis-net
        volumes:
            - redis-data:/data

networks:
  redis-net:
  notes-app_api-service-net:
  notes-app_ui-service-net:

volumes:
  redis-data: