version: '3'
services:
    api-service:
        build:
            context: ../api-service
            dockerfile: Dockerfile
        image: arturjs/notes-app_api-service:latest
        container_name: 'api-service'
        env_file: ../api-service/.env
        environment:
            - DOCKER_BUILD=true
        labels: 
            kompose.service.expose: 'api-service'
        ports:
            - "3001:3001"
        networks:
            internal-network:
                aliases:
                    - api-service
        depends_on:
            - redis

    ui-service:
        build:
            context: ../ui-service
            dockerfile: Dockerfile
        image: arturjs/notes-app_ui-service:0.0.1
        container_name: 'ui-service'
        env_file: ../ui-service/.env
        environment:
            - DOCKER_BUILD=true
            - API_URL=http://api-service:3001
        labels:
            kompose.service.type: LoadBalancer
        ports:
            - "8080:3000"
        networks:
            internal-network:
                aliases:
                    - ui-service

    redis:
        image: redis:4.0.5-alpine
        command: ['redis-server', '--appendonly', 'yes']
        networks:
            internal-network:
                aliases:
                    - redis
        volumes:
            - redis-data:/data

# http://andrewtarry.com/docker_compose/ - more info about networking in docker-compose
networks:
    internal-network:
        driver: bridge

volumes:
    redis-data:
