apiVersion: v1
data:
  API_URL: http://127.0.0.1:3001
  AUTH_SESSION_SECRET: SESSION_SECRET
  HOST: 127.0.0.1
  LOG_LEVEL: info
  NODE_ENV: production
  PORT: "3000"
  REDIS_HOST: 192.168.99.100
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui-service-ui-service--env
  name: ui-service-ui-service--env
